CC=gcc
CFLAGS=-Wall -Werror -Wextra
SOURCE1=cat.c
SOURCE2=../grep/grep.c
EXECUTABLE1=s21_cat
EXECUTABLE2=../grep/s21_grep

s21_cat: $(SOURCE1)
	$(CC) $(CFLAGS) $(SOURCE1) -o $(EXECUTABLE1)
	rm -rf *.o
